[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10.2.4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
